# This file is auto-generated by the dh-umc tools and should not be edited!
msgid ""
msgstr ""
"Project-Id-Version: univention-management-console-module-passwordreset\n"
"Report-Msgid-Bugs-To: packages@univention.de\n"
"POT-Creation-Date: 2017-02-22 13:02+0100\n"
"PO-Revision-Date: 2015-09-22 09:23+0200\n"
"Last-Translator: Univention GmbH <packages@univention.de>\n"
"Language-Team: Univention GmbH <packages@univention.de>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: umc/python/passwordreset/send_plugin.py:56
msgid "????"
msgstr "????"

#: umc/python/passwordreset/__init__.py:280
msgid "Changing contact data failed."
msgstr "Ändern der Kontaktdaten fehlgeschlagen."

#: umc/python/passwordreset/__init__.py:174
msgid ""
"Either username or password is incorrect or you are not allowed to use this "
"service."
msgstr ""
"Entweder stimmen Benutzername und Passwort nicht oder Sie haben keine "
"Berechtigung diesen Dienst zu nutzen."

#: umc/python/passwordreset/sending/send_email.py:73
msgid "Email"
msgstr "E-Mail"

#: umc/python/passwordreset/__init__.py:424
msgid "Error sending token: {}"
msgstr "Fehler beim Versenden des Tokens: {}"

#: umc/python/passwordreset/sending/send_with_external.py:75
msgid "External"
msgstr "Extern"

#: umc/python/passwordreset/__init__.py:376
msgid "Failed to change password."
msgstr "Passwortänderung fehlgeschlagen."

#: umc/python/passwordreset/sending/send_sms.py:88
msgid "Mobile number"
msgstr "Mobilfunknummer"

#: umc/python/passwordreset/__init__.py:195
msgid ""
"No address has been stored, where a password recovery token could be sent to."
msgstr ""
"Es wurden keine Kontaktadressen gefunden, an die ein Token "
"(Sicherheitsschlüssel) zur Wiederherstellung des Password geschickt werden "
"könnte."

#: umc/python/passwordreset/__init__.py:189
msgid ""
"No contact information is stored for this user. Resetting the password is "
"not possible."
msgstr ""
"Für diesen Benutzer wurden keine Kontaktinformationen hinterlegt. Das "
"Zurücksetzen des Passworts ist daher nicht möglich."

#: umc/python/passwordreset/__init__.py:279
msgid "Successfully changed your contact data."
msgstr "Ihre Kontaktdaten wurden erfolgreich geändert."

#: umc/python/passwordreset/__init__.py:375
msgid "Successfully changed your password."
msgstr "Ihr Passwort wurde erfolgreich geändert."

#: umc/python/passwordreset/__init__.py:329
msgid "Successfully send token."
msgstr "Der Token wurde erfolgreich versendet."

#: umc/python/passwordreset/__init__.py:166
msgid ""
"The allowed maximum number of connections to the server has been reached. "
"Please retry in {}."
msgstr ""
"Die erlaubte maximale Anzahl an Verbindungen zum Server wurde erreicht. "
"Bitte versuchen Sie es in {} erneut."

#: umc/python/passwordreset/__init__.py:76
#, python-format
msgid ""
"The connection to the server could not be established. Please try again "
"later. Error message was: %s"
msgstr "Die Verbindungen zum Server konnte nicht aufgebaut werden. Bitte versuchen Sie es später erneut. Fehlermeldung: %s"

#: umc/python/passwordreset/__init__.py:182
msgid ""
"The token you supplied is either expired or invalid. Please request a new "
"one."
msgstr ""
"Der Token (Sicherheitsschlüssel) den Sie angegeben haben ist entweder "
"abgelaufen oder ungültig. Bitte fordern Sie einen neuen an."

#: umc/python/passwordreset/__init__.py:294
msgid "Unknown recovery method '{}'."
msgstr "Unbekannte Wiederherstellungsfunktion '{}'."

#: umc/python/passwordreset/__init__.py:93
msgid "one hour"
msgstr "einer Stunde"

#: umc/python/passwordreset/__init__.py:88
msgid "one minute"
msgstr "einer Minute"

#: umc/python/passwordreset/__init__.py:95
msgid "{} hours"
msgstr "{} Stunden"

#: umc/python/passwordreset/__init__.py:91
msgid "{} minutes"
msgstr "{} Minuten"
