# This file is auto-generated by the dh-umc tools and should not be edited!
msgid ""
msgstr ""
"Project-Id-Version: univention-management-console-module-appcenter\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-03-22 15:12+0100\n"
"PO-Revision-Date: 2011-10-25 14:38+0200\n"
"Last-Translator: Univention GmbH <packages@univention.de>\n"
"Language-Team: Univention GmbH <packages@univention.de>\n"
"Language: German\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: umc/python/appcenter/util.py:171
#, python-format
msgid ""
"%s could not be downloaded. This seems to be a problem with the App Center "
"server. Please try again later."
msgstr ""
"Konnte %s nicht herunterladen. Das deutet auf ein Problem auf dem App Center-"
"Server hin. Bitte versuchen Sie es später noch einmal."

#: umc/python/appcenter/__init__.py:344
#, python-format
msgid "%s: Running tests"
msgstr "%s: Starte Tests"

#: umc/python/appcenter/__init__.py:226
msgid ""
"A conflict between the system network settings and the docker bridge default "
"network has been detected."
msgstr ""
"Es wurde ein Konflikt zwischen den Netzwerkeinstellungen des Systems und der "
"Docker Bridge entdeckt."

#: umc/python/appcenter/__init__.py:541 umc/python/appcenter/__init__.py:689
msgid "Another package operation is in progress"
msgstr "Zur Zeit wird eine andere Paketverarbeitung durchgeführt"

#: umc/python/appcenter/sanitizers.py:82
#, python-format
msgid "Any of %r must be given"
msgstr "Ein Wert aus %r muss gegeben sein"

#: umc/python/appcenter/sanitizers.py:52 umc/python/appcenter/sanitizers.py:56
#: umc/python/appcenter/sanitizers.py:60
msgid "Cannot connect to the LDAP service."
msgstr "Konnte nicht zum LDAP-Dienst verbinden."

#: umc/python/appcenter/__init__.py:263 umc/python/appcenter/__init__.py:278
#: umc/python/appcenter/__init__.py:416
#, python-format
msgid "Could not find an application for %s"
msgstr "Konnte keine Applikation für %s finden"

#: umc/python/appcenter/app_center.py:133
#, python-format
msgid "Error while contacting the App Center server. %s"
msgstr "Fehler bei der Kontaktaufnahme mit dem App Center-Server. %s"

#: umc/python/appcenter/__init__.py:364
#, python-format
msgid "Installing %s"
msgstr "Installiere %s"

#: umc/python/appcenter/app_center.py:1678
#, python-format
msgid "Installing LDAP packages on %s"
msgstr "Installiere LDAP Pakete auf %s"

#: umc/python/appcenter/__init__.py:196 umc/python/appcenter/__init__.py:242
msgid ""
"Make sure docker.io is installed, try starting the service with \"service "
"docker start\"."
msgstr ""
"Stellen Sie sicher, dass docker.io installiert ist. Starten Sie den Dienst "
"mit \"service docker start\"."

#: umc/python/appcenter/sanitizers.py:60
msgid "Maybe the machine password changed during the session."
msgstr ""
"Möglicherweise hat sich das Maschinenpasswort während der Sitzung geändert."

#: umc/python/appcenter/sanitizers.py:56
msgid "Maybe your password changed during the session."
msgstr "Möglicherweise hat sich Ihr Passwort während der Sitzung geändert."

#: umc/python/appcenter/__init__.py:82
msgid "Package not found in repository"
msgstr "Paket wurde in keinem Repository gefunden"

#: umc/python/appcenter/sanitizers.py:52
msgid "Please check the join state of the machine."
msgstr "Bitte überprüfen Sie den Status des Domänenbeitritts."

#: umc/python/appcenter/__init__.py:227
msgid ""
"Please either configure a different network for the docker bridge by setting "
"the UCR variable docker/daemon/default/opts/bip to a different network and "
"restart the system,"
msgstr ""
"Bitte konfigurieren Sie ein anderes Netzwerk für die Docker Bridge durch die "
"UCR Variable docker/daemon/default/opts/bip und ein Neustart des Systems,"

#: umc/python/appcenter/app_center.py:1593
msgid ""
"Registration of the application in LDAP failed. It will be retried every "
"time the App Center module is opened."
msgstr ""
"Die Registrierung der Applikation im LDAP ist fehlgeschlagen. Sie wird bei "
"jedem Öffnen des App Center Moduls wiederholt werden."

#: umc/python/appcenter/app_center.py:1097
#, python-format
msgid ""
"The application needs a %(needs)s-bit operating system. This server is "
"running a %(has)s-bit operating system."
msgstr ""
"Die Applikation benötigt ein %(needs)s-Bit-Betriebssystem. Dieser Server "
"läuft mit einem %(has)s-Bit-Betriebssystem."

#: umc/python/appcenter/sanitizers.py:56 umc/python/appcenter/sanitizers.py:60
msgid "The credentials provided were not accepted."
msgstr "Die Zugangsdaten wurden nicht akzeptiert."

#: umc/python/appcenter/__init__.py:196
msgid ""
"The docker service is not running! The App Center will not work properly."
msgstr ""
"Der Docker-Dienst läuft nicht! Das App Center wird nicht richtig "
"funktionieren."

#: umc/python/appcenter/sanitizers.py:52
msgid "The server seems to be lacking a proper password file."
msgstr "Dem Rechner scheint eine korrekte Passwortdatei zu fehlen."

#: umc/python/appcenter/sanitizers.py:93
msgid "There already is a component with this name"
msgstr "Es gibt bereits eine Komponente mit diesem Namen"

#: umc/python/appcenter/__init__.py:887
msgid ""
"There is no repository at this server (or at least none for the current UCS "
"version)"
msgstr ""
"Auf dem Server befindet sich kein Repository (oder zumindest keins für die "
"aktuelle UCS Version)"

#: umc/python/appcenter/util.py:173
msgid "This is a problem with the App Center server. Please try again later."
msgstr ""
"Das ist ein Problem auf dem App Center-Server. Bitte versuchen Sie es später "
"noch einmal."

#: umc/python/appcenter/util.py:187
#, python-format
msgid ""
"This is probably due to the DNS settings of your server. You may find help "
"at %s."
msgstr ""
"Grund sind wahrscheinlich die DNS-Einstellungen Ihres Servers. Sie finden "
"Hilfe unter %s."

#: umc/python/appcenter/util.py:184
#, python-format
msgid ""
"This may be a problem with the firewall or proxy of your system. You may "
"find help at %s."
msgstr ""
"Dies kann auf ein Problem mit einer auf Ihrem System eingerichteten Firewall "
"oder Proxy hindeuten. Sie finden Hilfe unter %s."

#: umc/python/appcenter/sanitizers.py:56 umc/python/appcenter/sanitizers.py:60
msgid "This may be solved by simply logging out and in again."
msgstr ""
"Das Problem kann vielleicht bereits durch ein Aus- und erneutes Einloggen "
"gelöst werden."

#: umc/python/appcenter/__init__.py:242
msgid "Unable to start the docker service!"
msgstr "Der Docker-Dienst konnte nicht gestartet werden!"

#: umc/python/appcenter/__init__.py:367
#, python-format
msgid "Uninstalling %s"
msgstr "Deinstalliere %s"

#: umc/python/appcenter/__init__.py:369
#, python-format
msgid "Upgrading %s"
msgstr "Aktualisiere %s"

#: umc/python/appcenter/util.py:183
#, python-format
msgid ""
"https://docs.software-univention.de/manual-%s.html#ip-config:"
"Web_proxy_for_caching_and_policy_management__virus_scan"
msgstr ""
"https://docs.software-univention.de/handbuch-%s.html#ip-config:Web-"
"Proxy_fuer_Caching_und_Policy_Management_Virenscan"

#: umc/python/appcenter/util.py:186
#, python-format
msgid "https://docs.software-univention.de/manual-%s.html#networks:dns"
msgstr "https://docs.software-univention.de/handbuch-%s.html#networks:dns"

#: umc/python/appcenter/__init__.py:733
msgid "installed"
msgstr "installiert"

#: umc/python/appcenter/__init__.py:735
msgid "not installed"
msgstr "nicht installiert"

#: umc/python/appcenter/__init__.py:228
msgid ""
"or disable the docker support in the AppCenter by setting appcenter/docker "
"to false."
msgstr ""
"oder deaktivieren Sie die Unterstützung für Docker im AppCenter indem die "
"UCR Variable appcenter/docker auf false gesetzt wird."

#: umc/python/appcenter/__init__.py:731
msgid "upgradable"
msgstr "aktualisierbar"
